[aws]
AWS_ACCESS_KEY_ID = "AKIAXYKJXLFKFTWEYY5W"
AWS_SECRET_ACCESS_KEY = "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"
AWS_DEFAULT_REGION = "us-east-1"

[mysql]
MYSQL_HOST=mck-db-ind.cbssaagyc4d6.us-east-1.rds.amazonaws.com
MYSQL_USER=admin
MYSQL_PASSWORD=Sindhu0303
MYSQL_DATABASE=industry_db
MYSQL_PORT=3306

