[aws]
AWS_ACCESS_KEY_ID = "AKIAXYKJXLFKFTWEYY5W"
AWS_SECRET_ACCESS_KEY = "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"
AWS_DEFAULT_REGION = "us-east-1"
[mysql]
user = "admin"
password = "Sindhu0303"
host = "mck-db-ind.cbssaagyc4d6.us-east-1.rds.amazonaws.com"
database = "industry_db"
port = 3306

